# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
      - main  # Specify the branch where you want the pipeline to trigger

jobs:
- job: InstallNuGetPackages
  displayName: 'Install NuGet Packages'
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: '3.x'
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'
    inputs:
      versionSpec: 'latest'
  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'  # Adjust the path pattern if necessary

 