trigger:
  branches:
    include:
      - main  # Specify the branch where you want the pipeline to trigger

jobs:
- job: InstallNuGetPackages
  displayName: 'Install NuGet Packages'
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'  # Adjust the path pattern if necessary
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
