# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

jobs:
- job: RunConsoleApp
  displayName: 'Run Console Application'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: '3.x'
  - script: dotnet build --configuration Release
    displayName: 'Build Console Application'
    workingDirectory: path/to/your/console/app
  - script: dotnet run --configuration Release --project path/to/your/console/app.csproj
    displayName: 'Run Console Application'
    workingDirectory: path/to/your/console/app